# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
np.random.random((3,3,3))

array([[[0.12779241, 0.27960925, 0.08020423],
        [0.47842702, 0.00633863, 0.28303771],
        [0.44526869, 0.72478909, 0.48028039]],

       [[0.26957452, 0.80998645, 0.50219019],
        [0.62698656, 0.75101814, 0.50132816],
        [0.5154079 , 0.13033114, 0.06906073]],

       [[0.78273449, 0.53118237, 0.66149642],
        [0.98477817, 0.74533491, 0.90317854],
        [0.26259006, 0.24992358, 0.64135418]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [10]:

np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [17]:
x = np.zeros((8,8), dtype = int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [21]:
a=np.random.random((5,5))
a=(a-np.mean(a))/(np.std(a))
a

array([[-0.68981124, -0.7715295 ,  0.05461414,  1.28522821, -1.41072041],
       [-0.19166942,  1.3903536 ,  1.26809825, -1.4406658 , -0.67023177],
       [ 1.25340832, -0.52715262,  0.97742381, -0.08543915, -0.04261907],
       [ 0.89569215, -0.37126092, -1.54693556,  1.13744912, -1.07667168],
       [-1.58301614,  0.36722952, -0.47536934,  0.83038809,  1.42320742]])

# 5.  How to find common values between two arrays?

In [23]:
array1 = np.array([0, 10, 20, 40, 60, 80, 33])
print("Array1: ",array1)
array2 = [10, 30, 40, 33]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60 80 33]
Array2:  [10, 30, 40, 33]
Common values between two arrays:
[10 33 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [34]:
yes= today-np.timedelta64(1)

today= np.datetime64('today')
yes= today-np.timedelta64(1)
tomrw= today+np.timedelta64(1)
print(yes)
print(today)
print(tomrw)

2020-08-06
2020-08-07
2020-08-08


# 7. Consider two random array A and B, check if they are equal

In [39]:
d = np.random.randint(1,10,6)
e = np.random.randint(1,10,6)
print(d,"\n", e)
equal = np.array_equal(d,e)
print(equal)

[8 7 6 7 3 8] 
 [2 5 6 1 6 4]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [41]:
y = np.random.random(10)
y[y.argmax()] = 0
print(y)

[0.74089104 0.02555221 0.         0.68715336 0.18943192 0.78920341
 0.48602245 0.47887039 0.01443586 0.70306328]


# 9. How to print all the values of an array?

In [50]:
t=np.zeros((50,50))
np.set_printoptions(threshold=np.inf)
print(t)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

# 10.Subtract the mean of each row of a matrix

In [55]:
X = np.random.rand(5, 10)
X1 = X - X.mean(axis=1).reshape(-1, 1)
X1

array([[ 0.09916764, -0.33726358,  0.35330198, -0.15783797, -0.42116051,
         0.06124035,  0.17520312,  0.15392509, -0.37788512,  0.451309  ],
       [ 0.07896318, -0.54418098,  0.21090355, -0.12716094,  0.01156095,
        -0.40422521,  0.34783082,  0.32580262,  0.34023998, -0.23973397],
       [ 0.21353426,  0.19205324, -0.47659828,  0.04761651,  0.33058425,
        -0.00559849, -0.11647368, -0.2400125 ,  0.4068525 , -0.35195782],
       [ 0.39368939, -0.31520947, -0.47718316,  0.34199019,  0.41682122,
         0.16676582,  0.35650791, -0.3264229 , -0.30650069, -0.25045831],
       [ 0.2340902 , -0.08197272, -0.05061131, -0.41833007,  0.37967655,
        -0.20363888, -0.41138374,  0.22164599, -0.01577742,  0.34630141]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [57]:
Z = np.ones(15)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 4. 2. 1. 3. 2. 3. 1. 2. 2. 1. 3. 3. 1. 2.]


In [58]:
np.add.at(Z, I, 1)
print(Z)

[9. 7. 3. 1. 5. 3. 5. 1. 3. 3. 1. 5. 5. 1. 3.]


# 12.How to get the diagonal of a dot product?

In [62]:
J = np.random.uniform(0,2,(3,3))
K = np.random.uniform(0,2,(3,3))
print(J)
print(K)
prod=np.diag(np.dot(J,K))
prod

[[0.6940894  1.2830133  0.35191661]
 [0.48998217 0.21675677 1.68957827]
 [0.13918823 0.33959189 0.35597045]]
[[0.33979804 0.65225465 0.26353032]
 [1.64403784 0.73102395 1.20099939]
 [1.95306771 1.41508749 1.21075392]]


array([3.0324896 , 2.86894861, 0.8755226 ])

# 13.How to find the most frequent value in an array?

In [63]:
H= np.random.randint(0,10,50)
print(H)
print(np.bincount(H).argmax())

[0 8 2 0 2 2 4 9 0 5 3 9 4 1 7 2 6 0 7 1 6 4 7 8 8 4 2 1 4 5 9 0 9 2 4 0 2
 7 2 4 4 2 7 5 3 2 2 9 2 1]
2


# 14.How to get the n largest values of an array

In [68]:
import numpy as np
s = np.random.rand(15)
print(s)
n = 5
print (s[np.argsort(s)[-n:]])

[0.2910269  0.98537955 0.37879296 0.56672187 0.57643944 0.47776997
 0.39917034 0.37460699 0.5671384  0.84854344 0.82319481 0.87174677
 0.56780258 0.27597255 0.20385899]
[0.57643944 0.82319481 0.84854344 0.87174677 0.98537955]


# 15.How to create a record array from a regular array?

In [73]:
Z = np.array([("pizza", 7, 34),
              ("straws", 10, 79)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'pizza',  7., 34) (b'straws', 10., 79)]
